apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 2m
  path: "./clusters/my-cluster/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
